In [1]:
import os
print(os.getcwd())
print(os.listdir('.')) # This shows files in your current folder

D:\DataAnalysis\Projects\Data Cleaning\notebooks
['.ipynb_checkpoints', 'Cleaning.ipynb', 'EDA.ipynb']

In [2]:
import pandas as pd

df = pd.read_csv("../dataset/supply_chain_data.csv")

df.head(20)

,order_id,product,city,supplier,price,quantity,order_date,delivery_date,warehouse,transport_cost,discount,customer_rating,returned,payment_method,delivery_status,notes
0,ORD1000,Monitor,Bengaluru,Supplier B,₹5132,11,2023-12-25,05/05/2023,WH2,unknown,0,NaN,No,UPI,delivered,NaN
1,ORD1001,Keyboard,hydrabad,Supplier B,32683 INR,2,06-10-2023,22/12/2023,NaN,200,ten,NaN,yes,UPI,Cancelled,late delivery
2,ORD1002,Tablet,hydrabad,Supplier B,₹1844,1,03-06-2023,06-27-2023,WH1,100,10,1.0,YES,NaN,Pending,urgent
3,ORD1003,Keyboard,Chennai,Supplier C,32869 INR,10,2023-11-05,09/10/2023,WH3,100,NaN,NaN,yes,card,Pending,NaN
4,ORD1004,Keyboard,Mumbai,NaN,32516 INR,12,2023-08-03,2023-09-19,NaN,NaN,NaN,3.0,NaN,card,delivered,NaN
5,ORD1005,Mobile,Hyderabad,Supplier C,35411,9,11-22-2023,04/06/2023,NaN,300rs,15,4.0,yes,card,Delivered,urgent
6,ORD1006,Tablet,Bengaluru,unknown,₹35031,11,22/09/2023,2023-06-09,WH2,300rs,15,NaN,no,Card,Pending,NaN
7,ORD1007,Tablet,Delhi,Supplier A,36702 INR,1,06/11/2023,11-16-2023,WH3,NaN,ten,3.0,NaN,card,Pending,late delivery
8,ORD1008,Tablet,Chennai,Supplier C,23523,10,2023-08-05,02-21-2023,WH3,NaN,15,1.0,yes,card,NaN,NaN
9,ORD1009,Keyboard,chen nai,Supplier B,40.942k,19,2023-12-25,2023-12-27,WH1,100,5,NaN,yes,UPI,NaN,check address
10,ORD1010,Monitor,Delhi,Supplier B,33983,11,2023-06-17,2023-12-29,WH1,300rs,10,2.0,No,Cash,Delivered,urgent
11,ORD1011,Tablet,mumbai,unknown,5776,3,2023-11-16,2023-03-14,NaN,100,10,1.0,yes,card,delivered,check address
12,ORD1012,Mouse,hydrabad,NaN,19724 INR,16,31/05/2023,21/07/2023,NaN,200,0,1.0,NaN,card,Cancelled,check address
13,ORD1013,Keyboard,banglore,Supplier A,15100 INR,10,2023-03-20,2023-11-02,WH2,200,ten,1.0,yes,Cash,Pending,NaN
14,ORD1014,Mobile,banglore,Supplier C,43.467k,2,02-07-2023,12-19-2023,NaN,NaN,15,3.0,No,card,Cancelled,late delivery
15,ORD1015,Monitor,chen nai,NaN,34884,19,2023-02-12,2023-02-18,WH2,300rs,15,5.0,YES,Cash,Cancelled,urgent
16,ORD1016,Mouse,banglore,NaN,41518 INR,4,2023-10-18,2023-06-22,WH2,200,5,3.0,No,Cash,Cancelled,urgent
17,ORD1017,Mouse,banglore,Supplier C,₹47348,16,2023-10-03,03-23-2023,WH3,300rs,15,5.0,No,card,Delivered,NaN
18,ORD1018,Mobile,Bengaluru,Supplier C,₹14932,6,03/04/2023,2023-09-10,WH3,300rs,15,3.0,yes,Card,delivered,check address
19,ORD1019,Monitor,Bengaluru,Supplier C,44700 INR,11,2023-06-04,12/06/2023,NaN,300,10,NaN,YES,card,delivered,urgent

In [3]:
df.duplicated().sum()
df["order_id"].duplicated().sum()

np.int64(200)

In [4]:
df.head()
df.info()
df.describe()
df.nunique()

<class 'pandas.DataFrame'>
RangeIndex: 12200 entries, 0 to 12199
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         12200 non-null  str
 1   product          12200 non-null  str
 2   city             12200 non-null  str
 3   supplier         9647 non-null   str
 4   price            12200 non-null  str
 5   quantity         12200 non-null  int64
 6   order_date       12200 non-null  str
 7   delivery_date    12200 non-null  str
 8   warehouse        9133 non-null   str
 9   transport_cost   10135 non-null  str
 10  discount         10143 non-null  str
 11  customer_rating  10106 non-null  float64
 12  returned         9714 non-null   str
 13  payment_method   9686 non-null   str
 14  delivery_status  9716 non-null   str
 15  notes            9205 non-null   str
dtypes: float64(1), int64(1), str(14)
memory usage: 1.5 MB

order_id           12000
product                6
city                  11
supplier               4
price              11663
quantity              19
order_date          1095
delivery_date       1095
warehouse              3
transport_cost         5
discount               5
customer_rating        5
returned               4
payment_method         4
delivery_status        4
notes                  3
dtype: int64

In [5]:
duplicates = df[df.duplicated(keep=False)]
duplicates.groupby(list(df.columns)).size().reset_index(name='count')

,order_id,product,city,supplier,price,quantity,order_date,delivery_date,warehouse,transport_cost,discount,customer_rating,returned,payment_method,delivery_status,notes,count
0,ORD10188,Keyboard,hydrabad,Supplier A,₹37409,5,10-06-2023,2023-03-01,WH2,300,15,1.0,No,Cash,Delivered,late delivery,2
1,ORD10602,Keyboard,Bangalore,Supplier A,46187 INR,1,2023-12-19,04-06-2023,WH3,200,15,3.0,no,Cash,Cancelled,late delivery,2
2,ORD11021,Monitor,Delhi,Supplier C,43760,16,07-20-2023,09-08-2023,WH3,100,ten,5.0,YES,card,Delivered,check address,2
3,ORD11371,Mobile,Delhi,Supplier A,₹2417,1,2023-08-20,06-05-2023,WH3,300,15,2.0,No,Card,Cancelled,check address,2
4,ORD11548,Monitor,chen nai,unknown,11347 INR,5,2023-10-17,2023-03-20,WH1,100,ten,3.0,no,Cash,delivered,urgent,2
5,ORD11783,Keyboard,Delhi,Supplier C,₹1233,8,04-08-2023,09/06/2023,WH2,300,5,2.0,No,Card,Pending,urgent,2
6,ORD12286,Laptop,Bangalore,Supplier B,₹37693,7,2023-09-16,2023-01-28,WH2,unknown,ten,4.0,yes,UPI,Cancelled,urgent,2
7,ORD12496,Tablet,Bangalore,unknown,23061,6,2023-11-19,2023-11-08,WH1,300,5,5.0,No,card,Pending,check address,2
8,ORD12799,Laptop,mumbai,unknown,49744 INR,14,12-03-2023,11-20-2023,WH2,300,5,5.0,No,Card,Delivered,urgent,2
9,ORD1516,Keyboard,Bangalore,Supplier C,₹17025,19,2023-09-06,09-26-2023,WH1,300rs,0,2.0,yes,Card,delivered,urgent,2
10,ORD1774,Laptop,Bangalore,Supplier B,47.267k,4,2023-06-20,2023-06-09,WH1,300rs,0,4.0,YES,card,Pending,late delivery,2
11,ORD2656,Tablet,Delhi,Supplier C,₹43387,10,06/08/2023,12-12-2023,WH3,200,0,2.0,YES,Cash,Delivered,check address,2
12,ORD3414,Mouse,Mumbai,unknown,₹40449,13,12-22-2023,2023-12-29,WH3,200,5,4.0,No,Card,Cancelled,urgent,2
13,ORD3699,Mobile,Mumbai,Supplier C,1443 INR,18,2023-04-04,10/05/2023,WH1,100,10,3.0,no,card,Cancelled,urgent,2
14,ORD4317,Tablet,mumbai,Supplier B,15.171k,3,2023-04-14,05/08/2023,WH3,200,10,4.0,yes,UPI,delivered,check address,2
15,ORD5051,Monitor,Hyderabad,Supplier A,48116,13,2023-11-02,05-26-2023,WH2,300rs,5,3.0,No,card,Pending,late delivery,2
16,ORD5064,Keyboard,Delhi,unknown,42658,9,09-27-2023,13/05/2023,WH3,300rs,10,4.0,No,Card,Pending,late delivery,2
17,ORD5350,Laptop,Chennai,Supplier C,2724 INR,1,2023-10-05,11-27-2023,WH2,300,ten,4.0,No,Card,Cancelled,late delivery,2
18,ORD5526,Laptop,Bangalore,unknown,48.05k,4,2023-08-28,2023-02-27,WH3,300,15,4.0,YES,Cash,Delivered,late delivery,2
19,ORD6737,Mobile,delhi,unknown,1.22k,3,2023-08-29,09-21-2023,WH3,100,5,3.0,No,Card,Pending,urgent,2
20,ORD6930,Laptop,mumbai,Supplier C,₹26826,1,2023-09-11,05-19-2023,WH1,unknown,15,4.0,no,Card,Delivered,late delivery,2
21,ORD7169,Laptop,hydrabad,unknown,45099 INR,10,2023-10-10,2023-08-21,WH2,300,ten,4.0,No,UPI,Pending,late delivery,2
22,ORD7197,Monitor,Bengaluru,unknown,₹41112,3,2023-08-13,05-01-2023,WH1,unknown,5,4.0,No,Card,Cancelled,late delivery,2
23,ORD7755,Tablet,delhi,Supplier B,19.484k,13,2023-12-20,2023-09-23,WH1,300,5,2.0,no,Card,delivered,urgent,2
24,ORD8121,Tablet,Delhi,Supplier C,12163,5,02-04-2023,10/04/2023,WH3,100,15,4.0,No,card,Delivered,urgent,2
25,ORD8277,Monitor,Mumbai,Supplier A,36021 INR,10,2023-10-09,2023-07-17,WH2,300rs,0,3.0,YES,UPI,delivered,check address,2
26,ORD8313,Mobile,Chennai,Supplier C,2446,3,29/07/2023,12-22-2023,WH2,unknown,ten,4.0,yes,UPI,Pending,check address,2
27,ORD9850,Tablet,mumbai,Supplier C,₹9342,19,2023-07-27,06-18-2023,WH1,100,10,4.0,no,Cash,Pending,check address,2

In [6]:
duplicates.nunique()

order_id           200
product              6
city                11
supplier             4
price              200
quantity            19
order_date         180
delivery_date      180
warehouse            3
transport_cost       5
discount             5
customer_rating      5
returned             4
payment_method       4
delivery_status      4
notes                3
dtype: int64

In [7]:
df["order_id"].duplicated().sum()

np.int64(200)

In [8]:
df.shape

(12200, 16)

In [9]:
df_temp = df.drop_duplicates()
df_temp.shape

df = df_temp

In [10]:
df.shape

(12000, 16)

In [11]:
duplicates  = df[df.duplicated(keep=False)]
duplicates.head(20)

Empty DataFrame
Columns: [order_id, product, city, supplier, price, quantity, order_date, delivery_date, warehouse, transport_cost, discount, customer_rating, returned, payment_method, delivery_status, notes]
Index: []

In [12]:
df[df.duplicated()].shape

(0, 16)

In [13]:
df = df.drop_duplicates()

In [14]:
df.shape

(12000, 16)

In [15]:
# Column cleaning of Price column

In [16]:
import pandas as pd
import numpy as np

def clean_price(value):
    if pd.isna(value):
        return np.nan

    value = str(value).lower().strip()

    #remove currency symbols and text
    value = value.replace('₹','').replace('inr','').strip()

    #handle 'k' (thousands)
    if 'k' in value:
        return float(value.replace('k',''))*1000

    #handle normal numbers
    try:
        return float(value)
    except:
        return np.nan

In [17]:
df["price_cleaned"] = df["price"].apply(clean_price)

In [18]:
df[["price", "price_cleaned"]].head(10)

       price  price_cleaned
0      ₹5132         5132.0
1  32683 INR        32683.0
2      ₹1844         1844.0
3  32869 INR        32869.0
4  32516 INR        32516.0
5      35411        35411.0
6     ₹35031        35031.0
7  36702 INR        36702.0
8      23523        23523.0
9    40.942k        40942.0

In [19]:
df["price_cleaned"].describe()

count    12000.000000
mean     25297.627417
std      14071.127311
min       1001.000000
25%      13170.000000
50%      25250.000000
75%      37441.500000
max      49995.000000
Name: price_cleaned, dtype: float64

In [20]:
df["price_cleaned"].isna().sum()

np.int64(0)

In [21]:
df["price_cleaned"] = df["price_cleaned"].round(2)

In [22]:
df["price_cleaned"].isna().sum()
# df["price_cleaned"].min()
# df["price_cleaned"].max()

np.int64(0)

In [23]:
df[~df["price"].astype(str).str.match(r'^[₹]?\d+(\.\d+)?k?$|^\d+\s*INR$', na=False)]

Empty DataFrame
Columns: [order_id, product, city, supplier, price, quantity, order_date, delivery_date, warehouse, transport_cost, discount, customer_rating, returned, payment_method, delivery_status, notes, price_cleaned]
Index: []

In [24]:
# Moving to City Column 
df["city"].unique()

<StringArray>
['Bengaluru',  'hydrabad',   'Chennai',    'Mumbai', 'Hyderabad',     'Delhi',
  'chen nai',   'mumbai ',  'banglore',     'delhi', 'Bangalore']
Length: 11, dtype: str

In [25]:
df["city"].nunique()

11

In [26]:
df["city_clean"] = (
    df["city"]
    .str.strip()      # remove spaces
    .str.lower()      # make lowercase
)

In [27]:
df["city_clean"].unique()

<StringArray>
['bengaluru',  'hydrabad',   'chennai',    'mumbai', 'hyderabad',     'delhi',
  'chen nai',  'banglore', 'bangalore']
Length: 9, dtype: str

In [28]:
city_mapping = {
    # Bangalore group
    "bangalore": "Bangalore",
    "banglore": "Bangalore",
    "bengaluru": "Bangalore",
    
    # Mumbai
    "mumbai": "Mumbai",
    
    # Delhi
    "delhi": "Delhi",
    
    # Chennai
    "chennai": "Chennai",
    "chen nai": "Chennai",
    
    # Hyderabad
    "hyderabad": "Hyderabad",
    "hydrabad": "Hyderabad"
}

In [29]:
df["city_final"] = df["city_clean"].map(city_mapping)

In [30]:
df["city_final"].isna().sum()

np.int64(0)

In [31]:
df[df["city_final"].isna()]["city_clean"].unique()

<StringArray>
[]
Length: 0, dtype: str

In [32]:
df["city_final"].value_counts()

city_final
Bangalore    3281
Delhi        2202
Mumbai       2192
Chennai      2184
Hyderabad    2141
Name: count, dtype: int64

# Date Column Cleaning

In [33]:
df[["order_date", "delivery_date"]].head(20)

    order_date delivery_date
0   2023-12-25    05/05/2023
1   06-10-2023    22/12/2023
2   03-06-2023    06-27-2023
3   2023-11-05    09/10/2023
4   2023-08-03    2023-09-19
5   11-22-2023    04/06/2023
6   22/09/2023    2023-06-09
7   06/11/2023    11-16-2023
8   2023-08-05    02-21-2023
9   2023-12-25    2023-12-27
10  2023-06-17    2023-12-29
11  2023-11-16    2023-03-14
12  31/05/2023    21/07/2023
13  2023-03-20    2023-11-02
14  02-07-2023    12-19-2023
15  2023-02-12    2023-02-18
16  2023-10-18    2023-06-22
17  2023-10-03    03-23-2023
18  03/04/2023    2023-09-10
19  2023-06-04    12/06/2023

# Clean function for Date

In [34]:
import pandas as pd

df["order_date_clean"] = pd.to_datetime(
    df["order_date"], 
    errors="coerce",
    format="mixed"
   
)

df["delivery_date_clean"] = pd.to_datetime(
    df["delivery_date"], 
    errors="coerce", 
    format="mixed"
   
)

In [35]:
# Force convert the cleaned columns to datetime objects
df['order_date_clean'] = pd.to_datetime(df['order_date_clean'], errors='coerce')
df['delivery_date_clean'] = pd.to_datetime(df['delivery_date_clean'], errors='coerce')

# Double check the types
print(df[['order_date_clean', 'delivery_date_clean']].dtypes)

order_date_clean       datetime64[us]
delivery_date_clean    datetime64[us]
dtype: object

In [36]:
df.shape

(12000, 21)

In [37]:
df[["order_date_clean", "delivery_date_clean"]].head(20)

   order_date_clean delivery_date_clean
0        2023-12-25          2023-05-05
1        2023-06-10          2023-12-22
2        2023-03-06          2023-06-27
3        2023-11-05          2023-09-10
4        2023-08-03          2023-09-19
5        2023-11-22          2023-04-06
6        2023-09-22          2023-06-09
7        2023-06-11          2023-11-16
8        2023-08-05          2023-02-21
9        2023-12-25          2023-12-27
10       2023-06-17          2023-12-29
11       2023-11-16          2023-03-14
12       2023-05-31          2023-07-21
13       2023-03-20          2023-11-02
14       2023-02-07          2023-12-19
15       2023-02-12          2023-02-18
16       2023-10-18          2023-06-22
17       2023-10-03          2023-03-23
18       2023-03-04          2023-09-10
19       2023-06-04          2023-12-06

# transport cost column

In [38]:
df["transport_cost"].unique()

<StringArray>
['unknown', '200', '100', nan, '300rs', '300']
Length: 6, dtype: str

In [39]:
import numpy as np

def clean_transport(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x).lower().strip()
    
    # remove text
    x = x.replace("rs", "").replace("₹", "")
    
    if x == "unknown":
        return np.nan
    
    try:
        return float(x)
    except:
        return np.nan

df["transport_cost_clean"] = df["transport_cost"].apply(clean_transport)

In [40]:
df["transport_cost_clean"].dtype
df["transport_cost_clean"].isna().sum()
df[["transport_cost", "transport_cost_clean"]].head(20)

   transport_cost  transport_cost_clean
0         unknown                   NaN
1             200                 200.0
2             100                 100.0
3             100                 100.0
4             NaN                   NaN
5           300rs                 300.0
6           300rs                 300.0
7             NaN                   NaN
8             NaN                   NaN
9             100                 100.0
10          300rs                 300.0
11            100                 100.0
12            200                 200.0
13            200                 200.0
14            NaN                   NaN
15          300rs                 300.0
16            200                 200.0
17          300rs                 300.0
18          300rs                 300.0
19            300                 300.0

# Clean discount column

In [41]:
def clean_discount(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x).lower().strip()
    
    # text to number
    if x == "ten":
        return 10
    
    try:
        return float(x)
    except:
        return np.nan

df["discount_clean"] = df["discount"].apply(clean_discount)

In [42]:
df[["discount", "discount_clean"]].head(20)

   discount  discount_clean
0         0             0.0
1       ten            10.0
2        10            10.0
3       NaN             NaN
4       NaN             NaN
5        15            15.0
6        15            15.0
7       ten            10.0
8        15            15.0
9         5             5.0
10       10            10.0
11       10            10.0
12        0             0.0
13      ten            10.0
14       15            15.0
15       15            15.0
16        5             5.0
17       15            15.0
18       15            15.0
19       10            10.0

In [43]:
df["discount_clean"].dtype
df["discount_clean"].isna().sum()

np.int64(2016)

# returned and payment_method columns

In [44]:
df["returned"].value_counts(dropna=False)
df["payment_method"].value_counts(dropna=False)

payment_method
NaN      2477
card     2430
Cash     2394
Card     2380
UPI      2319
Name: count, dtype: int64

In [45]:
df["returned"] = df["returned"].fillna("No")

In [46]:
df["payment_method"] = df["payment_method"].fillna("Unknown")

In [47]:
df.head()

,order_id,product,city,supplier,price,quantity,order_date,delivery_date,warehouse,transport_cost,...,payment_method,delivery_status,notes,price_cleaned,city_clean,city_final,order_date_clean,delivery_date_clean,transport_cost_clean,discount_clean
0,ORD1000,Monitor,Bengaluru,Supplier B,₹5132,11,2023-12-25,05/05/2023,WH2,unknown,...,UPI,delivered,NaN,5132.0,bengaluru,Bangalore,2023-12-25,2023-05-05,NaN,0.0
1,ORD1001,Keyboard,hydrabad,Supplier B,32683 INR,2,06-10-2023,22/12/2023,NaN,200,...,UPI,Cancelled,late delivery,32683.0,hydrabad,Hyderabad,2023-06-10,2023-12-22,200.0,10.0
2,ORD1002,Tablet,hydrabad,Supplier B,₹1844,1,03-06-2023,06-27-2023,WH1,100,...,Unknown,Pending,urgent,1844.0,hydrabad,Hyderabad,2023-03-06,2023-06-27,100.0,10.0
3,ORD1003,Keyboard,Chennai,Supplier C,32869 INR,10,2023-11-05,09/10/2023,WH3,100,...,card,Pending,NaN,32869.0,chennai,Chennai,2023-11-05,2023-09-10,100.0,NaN
4,ORD1004,Keyboard,Mumbai,NaN,32516 INR,12,2023-08-03,2023-09-19,NaN,NaN,...,card,delivered,NaN,32516.0,mumbai,Mumbai,2023-08-03,2023-09-19,NaN,NaN

In [48]:
df["returned"].isna().sum()
df["payment_method"].isna().sum()

np.int64(0)

In [49]:
df["payment_method"] = df["payment_method"].str.strip().str.title()
df["payment_method"] = df["payment_method"].fillna("Unknown")

In [50]:
df["returned"].value_counts(dropna=False)
df["payment_method"].value_counts(dropna=False)

payment_method
Card       4810
Unknown    2477
Cash       2394
Upi        2319
Name: count, dtype: int64

In [51]:
df["returned"] = df["returned"].str.strip().str.lower()
df["returned"] = df["returned"].map({
    "yes": "Yes",
    "no": "No"
})

In [52]:
df["returned"] = df["returned"].fillna("No")

In [53]:
df["returned"].value_counts()

returned
No     7238
Yes    4762
Name: count, dtype: int64

In [54]:
# df.duplicated().sum()

In [55]:
# df = df.drop_duplicates()
# df.shape

In [56]:
df["order_id"].duplicated().sum()

np.int64(0)

In [57]:
df.describe()

,quantity,customer_rating,price_cleaned,order_date_clean,delivery_date_clean,transport_cost_clean,discount_clean
count,12000.000000,9937.000000,12000.000000,12000,12000,7972.000000,9984.000000
mean,9.941333,2.985408,25297.627417,2023-07-01 12:06:50.400000,2023-07-01 15:30:28.800000,225.200702,7.976262
min,1.000000,1.000000,1001.000000,2023-01-01 00:00:00,2023-01-01 00:00:00,100.000000,0.000000
25%,5.000000,2.000000,13170.000000,2023-04-02 00:00:00,2023-03-31 00:00:00,100.000000,5.000000
50%,10.000000,3.000000,25250.000000,2023-07-01 00:00:00,2023-07-02 00:00:00,300.000000,10.000000
75%,15.000000,4.000000,37441.500000,2023-09-29 00:00:00,2023-10-01 00:00:00,300.000000,10.000000
max,19.000000,5.000000,49995.000000,2023-12-31 00:00:00,2023-12-31 00:00:00,300.000000,15.000000
std,5.481626,1.425727,14071.127311,NaN,NaN,83.132121,5.108121

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              12000 non-null  str
 1   product               12000 non-null  str
 2   city                  12000 non-null  str
 3   supplier              9473 non-null   str
 4   price                 12000 non-null  str
 5   quantity              12000 non-null  int64
 6   order_date            12000 non-null  str
 7   delivery_date         12000 non-null  str
 8   warehouse             8988 non-null   str
 9   transport_cost        9972 non-null   str
 10  discount              9984 non-null   str
 11  customer_rating       9937 non-null   float64
 12  returned              12000 non-null  str
 13  payment_method        12000 non-null  str
 14  delivery_status       9559 non-null   str
 15  notes                 9062 non-null   str
 16  price_cleaned         12000 non-null  float64
 17  city_clean            12000 non-null  str
 18  city_final            12000 non-null  str
 19  order_date_clean      12000 non-null  datetime64[us]
 20  delivery_date_clean   12000 non-null  datetime64[us]
 21  transport_cost_clean  7972 non-null   float64
 22  discount_clean        9984 non-null   float64
dtypes: datetime64[us](2), float64(4), int64(1), str(16)
memory usage: 2.1 MB

In [59]:
# Before this the data types of the columns should be cleaned

# df = df[df["price"] > 0]
# df = df[df["quantity"] > 0]
# df = df[df["transport_cost_clean"] >= 0]

In [60]:
df.isna().sum()

order_id                   0
product                    0
city                       0
supplier                2527
price                      0
quantity                   0
order_date                 0
delivery_date              0
warehouse               3012
transport_cost          2028
discount                2016
customer_rating         2063
returned                   0
payment_method             0
delivery_status         2441
notes                   2938
price_cleaned              0
city_clean                 0
city_final                 0
order_date_clean           0
delivery_date_clean        0
transport_cost_clean    4028
discount_clean          2016
dtype: int64

In [61]:
df_clean = df[[
    "order_id",
    "product",
    "city_final",
    "supplier",
    "price_cleaned",
    "quantity",
    "order_date_clean",
    "delivery_date_clean",
    "warehouse",
    "transport_cost_clean",
    "discount_clean",
    "customer_rating",
    "returned",
    "payment_method",
    "delivery_status",
    "notes"
]]

In [62]:
df_clean.isna().sum()

order_id                   0
product                    0
city_final                 0
supplier                2527
price_cleaned              0
quantity                   0
order_date_clean           0
delivery_date_clean        0
warehouse               3012
transport_cost_clean    4028
discount_clean          2016
customer_rating         2063
returned                   0
payment_method             0
delivery_status         2441
notes                   2938
dtype: int64

In [63]:
df_clean = df_clean.rename(columns={
    "city_final": "city",
    "transport_cost_clean": "transport_cost",
    "discount_clean": "discount",
    "order_date_clean":"order_date",
    "delivery_date_clean":"delivery_date",
    "price_cleaned":"price"
    
    
})

In [64]:
df_clean.shape

(12000, 16)

In [65]:
df.shape

(12000, 23)

In [66]:
print("Original shape:", df.shape)
print("Current shape:", df_clean.shape)

Original shape: (12000, 23)
Current shape: (12000, 16)

In [67]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         12000 non-null  str
 1   product          12000 non-null  str
 2   city             12000 non-null  str
 3   supplier         9473 non-null   str
 4   price            12000 non-null  float64
 5   quantity         12000 non-null  int64
 6   order_date       12000 non-null  datetime64[us]
 7   delivery_date    12000 non-null  datetime64[us]
 8   warehouse        8988 non-null   str
 9   transport_cost   7972 non-null   float64
 10  discount         9984 non-null   float64
 11  customer_rating  9937 non-null   float64
 12  returned         12000 non-null  str
 13  payment_method   12000 non-null  str
 14  delivery_status  9559 non-null   str
 15  notes            9062 non-null   str
dtypes: datetime64[us](2), float64(4), int64(1), str(9)
memory usage: 1.5 MB

In [68]:
df_clean.head()

,order_id,product,city,supplier,price,quantity,order_date,delivery_date,warehouse,transport_cost,discount,customer_rating,returned,payment_method,delivery_status,notes
0,ORD1000,Monitor,Bangalore,Supplier B,5132.0,11,2023-12-25,2023-05-05,WH2,NaN,0.0,NaN,No,Upi,delivered,NaN
1,ORD1001,Keyboard,Hyderabad,Supplier B,32683.0,2,2023-06-10,2023-12-22,NaN,200.0,10.0,NaN,Yes,Upi,Cancelled,late delivery
2,ORD1002,Tablet,Hyderabad,Supplier B,1844.0,1,2023-03-06,2023-06-27,WH1,100.0,10.0,1.0,Yes,Unknown,Pending,urgent
3,ORD1003,Keyboard,Chennai,Supplier C,32869.0,10,2023-11-05,2023-09-10,WH3,100.0,NaN,NaN,Yes,Card,Pending,NaN
4,ORD1004,Keyboard,Mumbai,NaN,32516.0,12,2023-08-03,2023-09-19,NaN,NaN,NaN,3.0,No,Card,delivered,NaN

In [69]:
# Filter the dataframe to only look at rows where the discount is missing
missing_discounts = df_clean[df_clean["discount"].isna()]

# Check the distribution across suppliers
print("Missing Discounts by Supplier:")
print(missing_discounts["supplier"].value_counts(dropna=False))

print("\n" + "-"*30 + "\n")

# Check the distribution across cities
print("Missing Discounts by City:")
print(missing_discounts["city"].value_counts(dropna=False))

Missing Discounts by Supplier:
supplier
Supplier C    426
NaN           423
unknown       407
Supplier B    394
Supplier A    366
Name: count, dtype: int64

------------------------------

Missing Discounts by City:
city
Bangalore    511
Delhi        403
Hyderabad    372
Mumbai       371
Chennai      359
Name: count, dtype: int64

# converting the discounts nan to 0 since the nan spread evenly and there is no single vendor or city with higest nan

In [70]:
# Fill missing discounts with 0
df_clean["discount"] = df_clean["discount"].fillna(0)

# Quick check to confirm they are gone
print("Remaining missing discounts:", df_clean["discount"].isna().sum())

Remaining missing discounts: 0

# Rating column checking between 1 and 5

In [71]:
# Check the unique values and their counts to ensure there are no weird ratings (like 6.0 or -1.0)
print(df_clean["customer_rating"].value_counts(dropna=False).sort_index())

customer_rating
1.0    2076
2.0    1928
3.0    2014
4.0    1903
5.0    2016
NaN    2063
Name: count, dtype: int64

# Removing nan from both supplier and warehouse replace with unknown

In [72]:
# Standardize missing values in warehouse
df_clean["warehouse"] = df_clean["warehouse"].fillna("Unknown")

# Standardize missing values in supplier (filling NaNs and capitalizing existing "unknown" strings)
df_clean["supplier"] = df_clean["supplier"].fillna("Unknown")
df_clean["supplier"] = df_clean["supplier"].replace("unknown", "Unknown")

# Quick check to confirm
print("Missing warehouses:", df_clean["warehouse"].isna().sum())
print("Missing suppliers:", df_clean["supplier"].isna().sum())

Missing warehouses: 0
Missing suppliers: 0

In [73]:
df_clean["quantity"].isna().sum()

np.int64(0)

# Transport cost column

In [74]:
# Filling Transport cost with grouped median since every city has its median transportation cost

In [75]:
# Check the median transport cost for each city
print("Median Transport Cost by City:")
print(df_clean.groupby("city")["transport_cost"].median())

print("\n" + "-"*30 + "\n")

# Let's also look at the overall median just in case
print("Overall Median Transport Cost:", df_clean["transport_cost"].median())

Median Transport Cost by City:
city
Bangalore    300.0
Chennai      300.0
Delhi        300.0
Hyderabad    300.0
Mumbai       200.0
Name: transport_cost, dtype: float64

------------------------------

Overall Median Transport Cost: 300.0

In [76]:
# fill the data with grouped median

# Fill missing transport costs with the median of their respective city
df_clean["transport_cost"] = df_clean["transport_cost"].fillna(
    df_clean.groupby("city")["transport_cost"].transform("median")
)

# Quick check to confirm they are gone
print("Remaining missing transport costs:", df_clean["transport_cost"].isna().sum())

Remaining missing transport costs: 0

In [77]:
df_clean.head()

,order_id,product,city,supplier,price,quantity,order_date,delivery_date,warehouse,transport_cost,discount,customer_rating,returned,payment_method,delivery_status,notes
0,ORD1000,Monitor,Bangalore,Supplier B,5132.0,11,2023-12-25,2023-05-05,WH2,300.0,0.0,NaN,No,Upi,delivered,NaN
1,ORD1001,Keyboard,Hyderabad,Supplier B,32683.0,2,2023-06-10,2023-12-22,Unknown,200.0,10.0,NaN,Yes,Upi,Cancelled,late delivery
2,ORD1002,Tablet,Hyderabad,Supplier B,1844.0,1,2023-03-06,2023-06-27,WH1,100.0,10.0,1.0,Yes,Unknown,Pending,urgent
3,ORD1003,Keyboard,Chennai,Supplier C,32869.0,10,2023-11-05,2023-09-10,WH3,100.0,0.0,NaN,Yes,Card,Pending,NaN
4,ORD1004,Keyboard,Mumbai,Unknown,32516.0,12,2023-08-03,2023-09-19,Unknown,200.0,0.0,3.0,No,Card,delivered,NaN

In [78]:
df_clean["delivery_status"].isna().sum()

np.int64(2441)

# filling delivery status nan to unknown and also notes nan to No Notes

In [79]:
# 1. Clean 'delivery_status': Make capitalization uniform (Title Case) and handle missing data
df_clean["delivery_status"] = df_clean["delivery_status"].str.strip().str.title()
df_clean["delivery_status"] = df_clean["delivery_status"].fillna("Unknown")

# 2. Clean 'notes': Fill missing comments with "No Notes"
df_clean["notes"] = df_clean["notes"].fillna("No Notes")

# 3. The Final Verification!
print(df_clean.isna().sum())

order_id              0
product               0
city                  0
supplier              0
price                 0
quantity              0
order_date            0
delivery_date         0
warehouse             0
transport_cost        0
discount              0
customer_rating    2063
returned              0
payment_method        0
delivery_status       0
notes                 0
dtype: int64

In [80]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         12000 non-null  str
 1   product          12000 non-null  str
 2   city             12000 non-null  str
 3   supplier         12000 non-null  str
 4   price            12000 non-null  float64
 5   quantity         12000 non-null  int64
 6   order_date       12000 non-null  datetime64[us]
 7   delivery_date    12000 non-null  datetime64[us]
 8   warehouse        12000 non-null  str
 9   transport_cost   12000 non-null  float64
 10  discount         12000 non-null  float64
 11  customer_rating  9937 non-null   float64
 12  returned         12000 non-null  str
 13  payment_method   12000 non-null  str
 14  delivery_status  12000 non-null  str
 15  notes            12000 non-null  str
dtypes: datetime64[us](2), float64(4), int64(1), str(9)
memory usage: 1.5 MB

In [81]:
# Export the cleaned dataframe to a new CSV file
# We use index=False so pandas doesn't write the row numbers (0, 1, 2...) as a new column
df_clean.to_csv("../dataset/supply_chain_data_cleaned.csv", index=False)

print("Data cleaning complete! File saved as 'supply_chain_data_cleaned.csv'")

Data cleaning complete! File saved as 'supply_chain_data_cleaned.csv'